---
title: "Week 10 - Practical"
sidebar: false
---


## Learning Outcome:

1.  Understand measurement accuracy concepts and their application to exercise testing and measurement

2.  Evaluate the feasibility of different tests according to environmental conditions and client characteristics

3.  Demonstrate basic data processing and analytical techniques

4.  Communicate test results and their implications to hypothetical client scenarios

<br>

## Practical Goals:

-   Develop understanding of internal vs objective markers of training load

-   Time permitting quick overview of more advanced techniques for performing systematic search           strategies


<br>

## Background:

Over the last two weeks in seminar material we have discussed the construct of **"Training Load"**. Importantly we can think of training load being made up of two sub dimensions **Internal** and **External** load. **Internal Load** can be further subdivided into **Objective** and **Subjective** markers.

**External load**: Can quite simply just been thought of as a measure of how much work was done. e.g. 5km of running, 1000 steps, 100m swim. 


**Internal load**: Is a measure of the bodies response to performing the external load. Most commonly used measures are Heart rate based indices that were discussed in Week 4. Internal load can also represent biochemical markers (Creatine Kinase, Lactic Acid), Hormonal responses (Testosterone, Cortisol) or Immunological markers (IGA, IL1,6). The above would be considered **objective** internal load makers whilst measures based on perception of effort of assessing mood such as Borg,Session RPE, Profile of Mood States, DALDA would be considered **subjective** makers of internal load. 

### Activity 

In this weeks activity we are going to use a combination of external load and internal load markers as measured via integrated GPS/IMU and HR device from the Polar Team System. This should help build your intuition around how interpreting both internal and external load can be useful in both categorising intensity of drills but also how 